config/routes.rb
Rails.application.routes.draw do
  # Routes for users
  resources :users, only: [:new, :create]

  # Routes for sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  delete 'session', to: 'sessions#destroy'
  
  resources :companies, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :games, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, :country, presence: { message: 'Please write something!'}
  validates :name, uniqueness: true

  has_many :involved_companies
  has_many :games, through: :involved_companies

  has_many :reviews, as: :reviewable
end

app/models/game.rb
class Game < ApplicationRecord
  validates :name, :category, presence: { message: 'Please write something!'}
  validates :name, uniqueness: true
  validates :rating, numericality: {
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 100,
  }
  
  has_many :involved_companies
  has_many :companies, through: :involved_companies
  has_and_belongs_to_many :platforms
  has_and_belongs_to_many :genres

  has_many :expansions, class_name: "Game", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Game", optional:true

  has_many :reviews, as: :reviewable

  enum category: {main_game: 0, expansion: 1}
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :games

  validates :name, presence: { message: 'Please write something!'}, uniqueness: true
end

app/models/involved_company.rb
class InvolvedCompany < ApplicationRecord
  belongs_to :company
  belongs_to :game

  validates :developer, :publisher, presence: { message: 'Please write something!'}
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_and_belongs_to_many :games

  enum category: {console: 0, arcade: 1, platform: 2, operating_system: 3, portable_console: 4, computer: 5}

  validates :name, :category, presence: { message: 'Please write something!'}
  validates :name, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  
  belongs_to :reviewable, polymorphic: true

  after_create do 
    user = User.find(self.user_id)
    user.update(review_count: user.review_count + 1)
  end

  after_destroy do
    user = User.find(self.user_id)
    user.update(review_count: user.review_count - 1)
  end

  validates :title, :body, presence: { message: 'Please write something!'}
  validates :title, length: {maximum: 40}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, :email, presence: { message: 'Please write something!'}, uniqueness: true

  has_many :reviews

  before_save do
    if self.review_count.nil?
      self.review_count = 0 
    end
  end

end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to '/welcome' unless logged_in?
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to company_path(@company)
    else
      render :new
    end
  end
  
  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to(@company)
    else
      render :edit
    end
  end

  def destroy
    company = Company.find(params[:id])
    company.destroy
    redirect_to companies_path
  end

  private
  def company_params
    params.require(:company).permit(:name, :description, :start_date, :country)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to game_path(@game)
    else
      render :new
    end
  end
  
  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    if @game.update(game_params)
      redirect_to(@game)
    else
      render :edit
    end
  end
  
  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to games_path
  end

  private
  def game_params
    params.require(:game).permit(:name, :summary, :release_date, :category, :rating, :parent_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/games'
    else
      redirect_to '/login', notice: "Username or password invalid"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/welcome'
  end

  skip_before_action :authorized, only: [:new, :create, :welcome]

  layout "welcome"
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/games'
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :birth_date, :email)
  end

  skip_before_action :authorized, only: [:new,:create]

  layout "welcome"
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <ul>
    <% @company.errors.full_messages.each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
  
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :start_date %><br />
    <%= f.text_field :start_date %>
  </p>
  <p>
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %> 

app/views/companies/edit.html.erb
<h1>Edit this Company</h1>

<%= render partial: 'form' %>

<%= link_to "Back to Companies", companies_path %>

app/views/companies/index.html.erb
<h1>All the Companies</h1>

<%= link_to "New company", new_company_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
    <tr>
      <td><%= company.name %></td>
      <td><%= link_to "Show", company %></td>
      <td><%= link_to "Edit", edit_company_path(company) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/new.html.erb
<h1>Create a New Company</h1>

<%= render partial: 'form' %>

<%= link_to "Back to Companies", companies_path %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>
<p><%= @company.description %></p>
<ul>
  <li>Start date: <%= @company.start_date %></li>
  <li>Country: <%= @company.country %></li>
</ul>

<%=link_to "Go back to Companies", companies_path%>
<%=link_to "Delete this Company", company_path(@company), method: :delete, data: { confirm: "Really delete the company?" } %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <ul>
  <% @game.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </p>
  <p>
    <%= f.label :release_date %><br />
    <%= f.text_field :release_date %>
  </p>
  <p>
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </p>
  <p>
    <%= f.label :parent_id %><br />
    <%= f.text_field :parent_id %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/games/edit.html.erb
<h1>Edit this Game</h1>

<%= render partial: 'form' %>

<%= link_to "Back to Games", games_path %>

app/views/games/index.html.erb
<h1>All the Games</h1>

<%= link_to "New game", new_game_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
    <tr>
      <td><%= game.name %></td>
      <td><%= game.rating %></td>
      <td><%= link_to "Show", game %></td>
      <td><%= link_to "Edit", edit_game_path(game) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/games/new.html.erb
<h1>Create a New Game</h1>

<%= render partial: 'form' %>

<%= link_to "Back to Games", games_path %>

app/views/games/show.html.erb
<h1><%= @game.name %></h1>
<p><%= @game.summary %></p>
<ul>
  <li>Rating: <%= @game.rating %></li>
  <li>Release Date: <%= @game.release_date %></li>
  <li>
    Platform(s): <%= @game.platforms.map { |platform| platform.name}.join(', ')
    %>
  </li>
  <li>
    Genre(s): <%= @game.genres.map { |genre| genre.name}.join(', ') %>
  </li>
</ul>

<%=link_to "Go back to Games", games_path%>
<%=link_to "Delete this Game", game_path(@game), method: :delete, data: { confirm: "Really delete the game?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CriticxAlpha</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p><%= notice %></p>
    <p><%= alert %></p>

    <% if current_user %> 
      Has iniciado sesión como <strong><%= current_user.username %></strong>! 
      <%= link_to 'Log out', session_path, method: :delete %> 
    <% else %> 
      <%= link_to 'Log in', login_path%>
      <%= link_to 'Sign up', new_user_path %> 
    <% end %> 
    <%= yield %>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CriticxAlphaViews</title>
    <%= csrf_meta_tags %> 
    <%= csp_meta_tag %> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p><%= notice %></p>
    <p><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<ul>
  <% @user.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>

<%= form_for @user do |f|%>
  <%= f.label :username%><br>
  <%= f.text_field :username%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password%><br>
  <%= f.label :birth_date%><br>
  <%= f.text_field :birth_date%><br>
  <%= f.label :email%><br>
  <%= f.text_field :email%><br>
  <%= f.submit %>
<%end%>